dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
  solc:
    remappings:
      - "@openzeppelin=/Users/elgun/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.4.2"
dotenv: .env
networks:
  default: "development"
  rinkeby:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
